name: draftman2
base: core18
version: '2.0.5'
summary: Draftman2 is a draft-management tool for writers
description: |
  Draftman2 is an organizational tool for writers. Although designed with creative writers in mind, Draftman2 is useful for any long-form writing project.
  
  Features:
  
    - Free and open source
    - Cross platform
    - hMinimalist
    - Bring your own editor
    - Markdown/plain-text based

grade: stable
confinement: classic

parts:
  draftman2:
    plugin: python
    python-version: python3
    requirements:
      - requirements.txt
    source-type: git
    source: https://github.com/jsseidel/draftman2
    override-build: |
      set -x
      snapcraftctl build
      mkdir -p $SNAPCRAFT_PART_INSTALL/opt/draftman2
      mkdir -p $SNAPCRAFT_PART_INSTALL/opt/draftman2/icon
      cp -r lib $SNAPCRAFT_PART_INSTALL/opt/draftman2/.
      cp -r 'Draftman2 Tutorial' $SNAPCRAFT_PART_INSTALL/opt/draftman2/.
      cp -r App.py draftman2.py draftman2.glade draftman2_py_run $SNAPCRAFT_PART_INSTALL/opt/draftman2/.
      cp -r icon/draftman2.png icon/draftman2_sm.png icon/file.svg icon/directory.svg icon/trash.svg $SNAPCRAFT_PART_INSTALL/opt/draftman2/icon/.
    build-packages:
      - git
      - python3
      - python3-pip
      - python3-gi
      - libgirepository1.0-dev
      - gcc
      - libcairo2-dev
      - pkg-config
      - python3-dev
      - gir1.2-gtk-3.0
      - python3-gi-cairo
      - python3-setuptools
    stage-packages:
      - python3
      - python3-pip
      - python3-gi
      - libgirepository1.0-dev
      - gcc
      - libcairo2-dev
      - pkg-config
      - python3-dev
      - gir1.2-gtk-3.0
      - python3-gi-cairo
      - python3-setuptools

apps:
  draftman2:
    extensions:
      - gnome-3-34
    command: snap/command-chain/desktop-launch $SNAP/opt/draftman2/draftman2_py_run
    plugs:
      - desktop
      - desktop-legacy
      - x11
      - home
