name: draftman2
base: core18
version: '2.0.3'
summary: Draftman2 is a draft-management tool for writers
description: |
  Draftman2 is an organizational tool for writers. Although designed with creative writers in mind, Draftman2 is useful for any long-form writing project.
  
  Features:
  
    - Free and open source
    - Cross platform
    - hMinimalist
    - Bring your own editor
    - Markdown/plain-text based

grade: stable
confinement: classic

parts:
  draftman2:
    plugin: python
    python-version: python3
    requirements:
      - requirements.txt
    source-type: git
    source: https://github.com/jsseidel/draftman2
    override-build: |
      set -x
      snapcraftctl build
      mkdir -p $SNAPCRAFT_PART_INSTALL/opt/draftman2
      mkdir -p $SNAPCRAFT_PART_INSTALL/opt/draftman2/icon
      cp -r lib $SNAPCRAFT_PART_INSTALL/opt/draftman2/.
      cp -r 'Draftman2 Tutorial' $SNAPCRAFT_PART_INSTALL/opt/draftman2/.
      cp -r App.py draftman2.py draftman2.glade draftman2_py_run $SNAPCRAFT_PART_INSTALL/opt/draftman2/.
      cp -r icon/draftman2.png icon/draftman2_sm.png icon/file.svg icon/directory.svg icon/trash.svg $SNAPCRAFT_PART_INSTALL/opt/draftman2/icon/.
    stage-packages:
      - git
      - python3
      - python3-gi

  desktop-gtk3:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    plugin: make
    make-parameters: ["FLAVOR=gtk3"]
    build-packages:
      - build-essential
      - libgtk-3-dev
    stage-packages:
      - libxkbcommon0  # XKB_CONFIG_ROOT
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libgtk-3-0
      - libgdk-pixbuf2.0-0
      - libglib2.0-bin
      - libgtk-3-bin
      - unity-gtk3-module
      - libappindicator3-1
      - locales-all
      - xdg-user-dirs
      - ibus-gtk3
      - libibus-1.0-5

apps:
  draftman2:
    command: bash $SNAP/bin/desktop-launch $SNAP/opt/draftman2/draftman2_py_run

